gates:
  - name: types
    command: pnpm type-check
    requirement: Zero TypeScript errors
    
  - name: tests
    command: pnpm test -- apps/web/components/cells/cost-breakdown-table-cell/__tests__/
    requirement: 80%+ coverage, all assertions verified
    
  - name: build
    command: pnpm build
    requirement: Production build succeeds
    
  - name: performance
    requirement: Load time ≤330ms (110% of 300ms target)
    measurement: React DevTools Profiler
    
  - name: accessibility
    requirement: WCAG AA compliance
    tools: Automated + manual review
