#!/bin/bash

echo "🔍 How to Get the Correct Supabase Connection Pooler URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If the connection still fails, you need the correct pooler URL from Supabase:"
echo ""
echo "1. Go to your Supabase dashboard:"
echo "   🔗 https://supabase.com/dashboard/project/bykrhpaqaxhyfrqfvbus/settings/database"
echo ""
echo "2. Find 'Connection string' section"
echo ""
echo "3. Look for 'Connection pooling' → 'Transaction mode'"
echo "   Should look like:"
echo "   postgresql://postgres.bykrhpaqaxhyfrqfvbus:[PASSWORD]@[REGION].pooler.supabase.com:6543/postgres"
echo ""
echo "4. The [REGION] part is what we need!"
echo "   Examples: aws-0-us-east-1, aws-0-us-west-1, aws-0-eu-west-1, etc."
echo ""
echo "5. Then update your DATABASE_URL in apps/web/.env.local:"
echo "   DATABASE_URL=postgresql://postgres.bykrhpaqaxhyfrqfvbus:Y%40seenH%40li2025@[CORRECT-REGION].pooler.supabase.com:6543/postgres"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Current guess: aws-0-us-west-1"
echo "   If wrong, you'll see 'Tenant or user not found' error"
echo ""
echo "📋 Password is already URL-encoded: Y%40seenH%40li2025 ✓"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
